#!/usr/bin/env bash
#This script loops from 1 to 10 and
luck=1;
while [ "$luck" -le 10 ]; do
    if [ "$luck" == 4 ]; then
        echo "bad luck";
    elif [ "$luck" == 8 ]; then
        echo "good luck";
    else
        echo "Best School";
    fi
    luck=$((luck + 1));
done
